// The built-in exercise library: name, primary muscle, other muscles worked, equipment.
// Written for this app. Custom exercises live in the app's data next to it.
export const MUSCLES = ["Chest", "Back", "Shoulders", "Biceps", "Triceps", "Forearms", "Abs", "Quads", "Hamstrings", "Glutes", "Calves", "Full body", "Cardio"];
export const EQUIPMENT = ["Barbell", "Dumbbell", "Machine", "Cable", "Bodyweight", "Kettlebell", "Band", "Other"];
export type Exercise = { id: string; name: string; muscle: string; other: string[]; equipment: string; custom?: boolean }
export const LIB: Exercise[] = ([
  ["bench-press", "Bench Press", "Chest", "Triceps,Shoulders", "Barbell"],
  ["incline-bench-press", "Incline Bench Press", "Chest", "Shoulders,Triceps", "Barbell"],
  ["decline-bench-press", "Decline Bench Press", "Chest", "Triceps", "Barbell"],
  ["db-bench-press", "Dumbbell Bench Press", "Chest", "Triceps,Shoulders", "Dumbbell"],
  ["incline-db-press", "Incline Dumbbell Press", "Chest", "Shoulders,Triceps", "Dumbbell"],
  ["db-fly", "Dumbbell Fly", "Chest", "Shoulders", "Dumbbell"],
  ["cable-fly", "Cable Fly", "Chest", "Shoulders", "Cable"],
  ["pec-deck", "Pec Deck", "Chest", "", "Machine"],
  ["chest-press-machine", "Chest Press Machine", "Chest", "Triceps", "Machine"],
  ["push-up", "Push-up", "Chest", "Triceps,Shoulders,Abs", "Bodyweight"],
  ["dip", "Dip", "Chest", "Triceps,Shoulders", "Bodyweight"],
  ["deadlift", "Deadlift", "Back", "Hamstrings,Glutes,Forearms", "Barbell"],
  ["romanian-deadlift", "Romanian Deadlift", "Hamstrings", "Glutes,Back", "Barbell"],
  ["db-romanian-deadlift", "Dumbbell Romanian Deadlift", "Hamstrings", "Glutes,Back", "Dumbbell"],
  ["barbell-row", "Barbell Row", "Back", "Biceps,Forearms", "Barbell"],
  ["pendlay-row", "Pendlay Row", "Back", "Biceps", "Barbell"],
  ["db-row", "One-arm Dumbbell Row", "Back", "Biceps", "Dumbbell"],
  ["seated-cable-row", "Seated Cable Row", "Back", "Biceps", "Cable"],
  ["lat-pulldown", "Lat Pulldown", "Back", "Biceps", "Cable"],
  ["close-grip-pulldown", "Close-grip Pulldown", "Back", "Biceps", "Cable"],
  ["pull-up", "Pull-up", "Back", "Biceps,Forearms", "Bodyweight"],
  ["chin-up", "Chin-up", "Back", "Biceps", "Bodyweight"],
  ["assisted-pull-up", "Assisted Pull-up", "Back", "Biceps", "Machine"],
  ["t-bar-row", "T-bar Row", "Back", "Biceps", "Barbell"],
  ["chest-supported-row", "Chest-supported Row", "Back", "Biceps", "Machine"],
  ["face-pull", "Face Pull", "Shoulders", "Back", "Cable"],
  ["straight-arm-pulldown", "Straight-arm Pulldown", "Back", "", "Cable"],
  ["back-extension", "Back Extension", "Back", "Glutes,Hamstrings", "Bodyweight"],
  ["good-morning", "Good Morning", "Hamstrings", "Back,Glutes", "Barbell"],
  ["shrug", "Barbell Shrug", "Back", "Forearms", "Barbell"],
  ["db-shrug", "Dumbbell Shrug", "Back", "Forearms", "Dumbbell"],
  ["overhead-press", "Overhead Press", "Shoulders", "Triceps", "Barbell"],
  ["seated-db-press", "Seated Dumbbell Press", "Shoulders", "Triceps", "Dumbbell"],
  ["arnold-press", "Arnold Press", "Shoulders", "Triceps", "Dumbbell"],
  ["shoulder-press-machine", "Shoulder Press Machine", "Shoulders", "Triceps", "Machine"],
  ["lateral-raise", "Lateral Raise", "Shoulders", "", "Dumbbell"],
  ["cable-lateral-raise", "Cable Lateral Raise", "Shoulders", "", "Cable"],
  ["front-raise", "Front Raise", "Shoulders", "", "Dumbbell"],
  ["rear-delt-fly", "Rear Delt Fly", "Shoulders", "Back", "Dumbbell"],
  ["reverse-pec-deck", "Reverse Pec Deck", "Shoulders", "Back", "Machine"],
  ["upright-row", "Upright Row", "Shoulders", "Back", "Barbell"],
  ["push-press", "Push Press", "Shoulders", "Triceps,Quads", "Barbell"],
  ["barbell-curl", "Barbell Curl", "Biceps", "Forearms", "Barbell"],
  ["ez-bar-curl", "EZ-bar Curl", "Biceps", "Forearms", "Barbell"],
  ["db-curl", "Dumbbell Curl", "Biceps", "Forearms", "Dumbbell"],
  ["hammer-curl", "Hammer Curl", "Biceps", "Forearms", "Dumbbell"],
  ["incline-db-curl", "Incline Dumbbell Curl", "Biceps", "", "Dumbbell"],
  ["preacher-curl", "Preacher Curl", "Biceps", "", "Machine"],
  ["cable-curl", "Cable Curl", "Biceps", "Forearms", "Cable"],
  ["concentration-curl", "Concentration Curl", "Biceps", "", "Dumbbell"],
  ["triceps-pushdown", "Triceps Pushdown", "Triceps", "", "Cable"],
  ["rope-pushdown", "Rope Pushdown", "Triceps", "", "Cable"],
  ["overhead-triceps-extension", "Overhead Triceps Extension", "Triceps", "", "Cable"],
  ["skull-crusher", "Skull Crusher", "Triceps", "", "Barbell"],
  ["close-grip-bench", "Close-grip Bench Press", "Triceps", "Chest,Shoulders", "Barbell"],
  ["db-kickback", "Dumbbell Kickback", "Triceps", "", "Dumbbell"],
  ["bench-dip", "Bench Dip", "Triceps", "Chest", "Bodyweight"],
  ["wrist-curl", "Wrist Curl", "Forearms", "", "Barbell"],
  ["reverse-curl", "Reverse Curl", "Forearms", "Biceps", "Barbell"],
  ["farmers-carry", "Farmer's Carry", "Forearms", "Full body", "Dumbbell"],
  ["back-squat", "Back Squat", "Quads", "Glutes,Hamstrings", "Barbell"],
  ["front-squat", "Front Squat", "Quads", "Glutes,Abs", "Barbell"],
  ["goblet-squat", "Goblet Squat", "Quads", "Glutes", "Dumbbell"],
  ["hack-squat", "Hack Squat", "Quads", "Glutes", "Machine"],
  ["leg-press", "Leg Press", "Quads", "Glutes,Hamstrings", "Machine"],
  ["leg-extension", "Leg Extension", "Quads", "", "Machine"],
  ["bulgarian-split-squat", "Bulgarian Split Squat", "Quads", "Glutes", "Dumbbell"],
  ["walking-lunge", "Walking Lunge", "Quads", "Glutes,Hamstrings", "Dumbbell"],
  ["reverse-lunge", "Reverse Lunge", "Quads", "Glutes", "Dumbbell"],
  ["step-up", "Step-up", "Quads", "Glutes", "Dumbbell"],
  ["pistol-squat", "Pistol Squat", "Quads", "Glutes", "Bodyweight"],
  ["leg-curl", "Lying Leg Curl", "Hamstrings", "Calves", "Machine"],
  ["seated-leg-curl", "Seated Leg Curl", "Hamstrings", "", "Machine"],
  ["nordic-curl", "Nordic Curl", "Hamstrings", "", "Bodyweight"],
  ["hip-thrust", "Hip Thrust", "Glutes", "Hamstrings", "Barbell"],
  ["glute-bridge", "Glute Bridge", "Glutes", "Hamstrings", "Bodyweight"],
  ["cable-kickback", "Cable Glute Kickback", "Glutes", "", "Cable"],
  ["hip-abduction", "Hip Abduction", "Glutes", "", "Machine"],
  ["sumo-deadlift", "Sumo Deadlift", "Glutes", "Quads,Back,Hamstrings", "Barbell"],
  ["trap-bar-deadlift", "Trap Bar Deadlift", "Quads", "Glutes,Back,Hamstrings", "Barbell"],
  ["standing-calf-raise", "Standing Calf Raise", "Calves", "", "Machine"],
  ["seated-calf-raise", "Seated Calf Raise", "Calves", "", "Machine"],
  ["db-calf-raise", "Dumbbell Calf Raise", "Calves", "", "Dumbbell"],
  ["plank", "Plank", "Abs", "Shoulders", "Bodyweight"],
  ["side-plank", "Side Plank", "Abs", "", "Bodyweight"],
  ["crunch", "Crunch", "Abs", "", "Bodyweight"],
  ["cable-crunch", "Cable Crunch", "Abs", "", "Cable"],
  ["hanging-leg-raise", "Hanging Leg Raise", "Abs", "Forearms", "Bodyweight"],
  ["ab-wheel", "Ab Wheel Rollout", "Abs", "Shoulders", "Other"],
  ["russian-twist", "Russian Twist", "Abs", "", "Bodyweight"],
  ["pallof-press", "Pallof Press", "Abs", "", "Cable"],
  ["kb-swing", "Kettlebell Swing", "Glutes", "Hamstrings,Back", "Kettlebell"],
  ["kb-goblet-squat", "Kettlebell Goblet Squat", "Quads", "Glutes", "Kettlebell"],
  ["turkish-get-up", "Turkish Get-up", "Full body", "Shoulders,Abs", "Kettlebell"],
  ["power-clean", "Power Clean", "Full body", "Back,Quads,Glutes", "Barbell"],
  ["thruster", "Thruster", "Full body", "Quads,Shoulders", "Barbell"],
  ["burpee", "Burpee", "Full body", "Chest,Quads", "Bodyweight"],
  ["band-pull-apart", "Band Pull-apart", "Shoulders", "Back", "Band"],
  ["rowing-machine", "Rowing Machine", "Cardio", "Back,Quads", "Machine"],
  ["treadmill", "Treadmill Run", "Cardio", "Quads,Calves", "Machine"],
  ["bike", "Stationary Bike", "Cardio", "Quads", "Machine"],
  ["jump-rope", "Jump Rope", "Cardio", "Calves", "Other"],
] as string[][]).map(([id, name, muscle, other, equipment]) => ({ id, name, muscle, other: other ? other.split(",") : [], equipment }))
