// Note apps (prototype): compiles what the AI tooling compiles at write time, for the demos and the
// amber-ui kit. The same esbuild-wasm transform and options as the contract:
//   deno run -A scripts/build-app.ts project <dir> <out.json>   a project folder -> {"amberApp": 1, files, compiled}
//   deno run -A scripts/build-app.ts kit                          amber-ui/ -> Pane/Resources/AppLibraries/amber-ui.json
import * as esbuild from "npm:esbuild-wasm@0.24.0";
import { walk } from "jsr:@std/fs@1/walk";
import { relative } from "jsr:@std/path@1";

await esbuild.initialize({});
// React projects (anything importing "react") compile for react/jsx-runtime, which the import map
// points at preact/compat; Preact projects for preact/jsx-runtime.
export const OPTIONS = { jsx: "automatic", jsxImportSource: "react", format: "esm", target: "es2020" } as const;
const loader = (p: string) => p.endsWith(".tsx") ? "tsx" : p.endsWith(".ts") ? "ts" : p.endsWith(".jsx") ? "jsx" : null;

async function compileDir(dir: string, jsxImportSource?: string) {
  const files: Record<string, string> = {}, compiled: Record<string, string> = {};
  for await (const e of walk(dir, { includeDirs: false })) files["/" + relative(dir, e.path)] = await Deno.readTextFile(e.path);
  const react = jsxImportSource ?? (Object.values(files).some((t) => /from\s+["']react["']|from\s+["']react-dom/.test(t)) ? "react" : "preact");
  for (const [path, text] of Object.entries(files)) {
    const l = loader(path);
    if (!l) continue;
    // CSS imported from a module (Vite style) is served as a module that adds the stylesheet.
    compiled[path] = (await esbuild.transform(text, { ...OPTIONS, jsxImportSource: react, loader: l, sourcefile: path })).code
      .replace(/(import\s*(?:[^"';]*from\s*)?)"([^"]+\.css)"/g, '$1"$2?import"');
  }
  // Tailwind: a stylesheet that starts from "tailwindcss" is compiled against the project's files.
  for (const [path, text] of Object.entries(files)) {
    if (!path.endsWith(".css") || !/@import\s+["']tailwindcss["']/.test(text)) continue;
    const cli = new URL("../app-stack/node_modules/@tailwindcss/cli/dist/index.mjs", import.meta.url).pathname;
    const out = await new Deno.Command("node", { args: [cli, "-i", "." + path, "--minify"], cwd: dir, stdout: "piped", stderr: "piped",
      env: { NODE_PATH: new URL("../app-stack/node_modules", import.meta.url).pathname } }).output();
    if (!out.success) throw new Error(new TextDecoder().decode(out.stderr));
    compiled[path] = new TextDecoder().decode(out.stdout);
  }
  return { files, compiled };
}

const [mode, a, b] = Deno.args;
if (mode === "project") {
  const { files, compiled } = await compileDir(a);
  await Deno.writeTextFile(b, JSON.stringify({ amberApp: 1, files, compiled }));
  console.log(`${Object.keys(files).length} files, ${Object.keys(compiled).length} compiled, ${JSON.stringify({ files, compiled }).length} bytes`);
} else if (mode === "kit") {
  const { files, compiled } = await compileDir("amber-ui/src", "preact");
  const css = await Deno.readTextFile("amber-ui/amber-ui.css");
  const strip = (o: Record<string, string>) => Object.fromEntries(Object.entries(o).map(([k, v]) => [k.slice(1), v]));
  // .js files aren't compiled: they are served as they are.
  for (const [k, v] of Object.entries(files)) if (k.endsWith(".js")) compiled[k] = v;
  await Deno.writeTextFile("Pane/Resources/AppLibraries/amber-ui.json", JSON.stringify({ version: "1.0.0", src: strip(files), compiled: strip(compiled), css }, null, 1));
  // The same sources for the AI tooling (copy a component into an app, show the kit's styles).
  await Deno.writeTextFile("supabase/functions/mcp/amber-ui.ts", "// Generated by scripts/build-app.ts kit from amber-ui/: don't edit.\n" +
    `export const AMBER_UI = ${JSON.stringify({ version: "1.0.0", src: strip(files), css }, null, 1)} as const;\n`);
  console.log(`amber-ui: ${Object.keys(files).length} files`);
}
esbuild.stop();
