// Note apps (prototype): compiles what the AI tooling compiles at write time, for the demos and the
// amber-ui kit. The same esbuild-wasm transform and options as the contract:
//   deno run -A scripts/build-app.ts project <dir> <out.json>   a project folder -> {"amberApp": 1, files, compiled}
//   deno run -A scripts/build-app.ts kit                          amber-ui/ -> Pane/Resources/AppLibraries/amber-ui.json
import * as esbuild from "npm:esbuild-wasm@0.24.0";
import { walk } from "jsr:@std/fs@1/walk";
import { relative } from "jsr:@std/path@1";

await esbuild.initialize({});
export const OPTIONS = { jsx: "automatic", jsxImportSource: "preact", format: "esm", target: "es2020" } as const;
const loader = (p: string) => p.endsWith(".tsx") ? "tsx" : p.endsWith(".ts") ? "ts" : p.endsWith(".jsx") ? "jsx" : null;

async function compileDir(dir: string) {
  const files: Record<string, string> = {}, compiled: Record<string, string> = {};
  for await (const e of walk(dir, { includeDirs: false })) {
    const path = "/" + relative(dir, e.path);
    const text = await Deno.readTextFile(e.path);
    files[path] = text;
    const l = loader(path);
    if (l) compiled[path] = (await esbuild.transform(text, { ...OPTIONS, loader: l, sourcefile: path })).code;
  }
  return { files, compiled };
}

const [mode, a, b] = Deno.args;
if (mode === "project") {
  const { files, compiled } = await compileDir(a);
  await Deno.writeTextFile(b, JSON.stringify({ amberApp: 1, files, compiled }));
  console.log(`${Object.keys(files).length} files, ${Object.keys(compiled).length} compiled, ${JSON.stringify({ files, compiled }).length} bytes`);
} else if (mode === "kit") {
  const { files, compiled } = await compileDir("amber-ui/src");
  const css = await Deno.readTextFile("amber-ui/amber-ui.css");
  const strip = (o: Record<string, string>) => Object.fromEntries(Object.entries(o).map(([k, v]) => [k.slice(1), v]));
  // .js files aren't compiled: they are served as they are.
  for (const [k, v] of Object.entries(files)) if (k.endsWith(".js")) compiled[k] = v;
  await Deno.writeTextFile("Pane/Resources/AppLibraries/amber-ui.json", JSON.stringify({ version: "1.0.0", src: strip(files), compiled: strip(compiled), css }, null, 1));
  // The same sources for the AI tooling (copy a component into an app, show the kit's styles).
  await Deno.writeTextFile("supabase/functions/mcp/amber-ui.ts", "// Generated by scripts/build-app.ts kit from amber-ui/: don't edit.\n" +
    `export const AMBER_UI = ${JSON.stringify({ version: "1.0.0", src: strip(files), css }, null, 1)} as const;\n`);
  console.log(`amber-ui: ${Object.keys(files).length} files`);
}
esbuild.stop();
